<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Mh extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Mh_model');
    } 

    /*
     * Listing of mhs
     */
    function index()
    {
        $data['mhs'] = $this->Mh_model->get_all_mhs();
        
        $data['_view'] = 'mh/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new mh
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'password' => $this->input->post('password'),
				'email' => $this->input->post('email'),
				'nama' => $this->input->post('nama'),
				'ttl' => $this->input->post('ttl'),
				'alamat' => $this->input->post('alamat'),
				'nohp' => $this->input->post('nohp'),
				'asal_sekolah' => $this->input->post('asal_sekolah'),
				'nama_ortu' => $this->input->post('nama_ortu'),
				'nohp_ortu' => $this->input->post('nohp_ortu'),
				'agama' => $this->input->post('agama'),
				'is_activated' => $this->input->post('is_activated'),
            );
            
            $mh_id = $this->Mh_model->add_mh($params);
            redirect('auth/login');
        }
        else
        {            
            $data['_view'] = 'mh/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    function add2()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
                'password' => $this->input->post('password'),
                'email' => $this->input->post('email'),
                'nama' => $this->input->post('nama'),
                'ttl' => $this->input->post('ttl'),
                'alamat' => $this->input->post('alamat'),
                'nohp' => $this->input->post('nohp'),
                'asal_sekolah' => $this->input->post('asal_sekolah'),
                'nama_ortu' => $this->input->post('nama_ortu'),
                'nohp_ortu' => $this->input->post('nohp_ortu'),
                'agama' => $this->input->post('agama'),
                'is_activated' => $this->input->post('is_activated'),
            );
                
            $mh_id = $this->Mh_model->add_mh($params);
            redirect('auth/login');
        }
        else
        {            
            $this->load->view('daftar');
        }
    } 
    /*
     * Editing a mh
     */
    function edit($npm)
    {   
        // check if the mh exists before trying to edit it
        $data['mh'] = $this->Mh_model->get_mh($npm);
        
        if(isset($data['mh']['npm']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'password' => $this->input->post('password'),
					'email' => $this->input->post('email'),
					'nama' => $this->input->post('nama'),
					'ttl' => $this->input->post('ttl'),
					'alamat' => $this->input->post('alamat'),
					'nohp' => $this->input->post('nohp'),
					'asal_sekolah' => $this->input->post('asal_sekolah'),
					'nama_ortu' => $this->input->post('nama_ortu'),
					'nohp_ortu' => $this->input->post('nohp_ortu'),
					'agama' => $this->input->post('agama'),
					'is_activated' => $this->input->post('is_activated'),
                );

                $this->Mh_model->update_mh($npm,$params);            
                redirect('mh/index');
            }
            else
            {
                $data['_view'] = 'mh/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The mh you are trying to edit does not exist.');
    } 

    /*
     * Deleting mh
     */
    function remove($npm)
    {
        $mh = $this->Mh_model->get_mh($npm);

        // check if the mh exists before trying to delete it
        if(isset($mh['npm']))
        {
            $this->Mh_model->delete_mh($npm);
            redirect('mh/index');
        }
        else
            show_error('The mh you are trying to delete does not exist.');
    }
    
}
